name: 🐛 Bug Report
description: File a bug report
title: '[Bug]: '
labels: ['bug']
body:
    - type: markdown
      attributes:
          value: |
              **Thanks for reporting!** Please provide as much detail as possible to help us resolve it quickly.
    - type: input
      id: version
      attributes:
          label: Affected version
          description: 'Which version has this bug?'
      validations:
          required: true
    - type: input
      id: version
      attributes:
          label: Affected config
          description: 'In which config have you encountered this bug?'
      validations:
          required: true
    - type: textarea
      id: steps
      attributes:
          label: Steps to Reproduce
          description: 'Step-by-step guide to trigger the bug'
      validations:
          required: true
    - type: textarea
      id: logs
      attributes:
          label: Error Logs
          description: 'Paste console errors or stack traces (wrap in ``` for formatting)'
          render: shell
      validations:
          required: true
    - type: checkboxes
      id: confirmations
      attributes:
          label: Checklist
          description: 'Please confirm the following before submitting.'
          options:
              - label: I've searched for existing issues
                required: true
              - label: I've included all relevant details
                required: true
              - label: I've tested it on the latest version
                required: true
