export { default as applyPrettier } from './applyPrettier'
export { default as findTSConfigs } from './findTSConfigs'
export { default as parseIgnoreFiles } from './parseIgnoreFiles'
export { default as patchVSCode } from './patchVSCode'
export { default as updateBrowserslist } from './updateBrowserslist'
