export { default as applyPrettier } from './applyPrettier'
export { default as findTSConfigs } from './findTSConfigs'
export { default as parseIgnoreFile } from './parseIgnoreFile'
export { default as patchVSCode } from './patchVSCode'
export { default as updateBrowserslist } from './updateBrowserslist'
