name: Release & Publish to NPM
on: workflow_dispatch
permissions: write-all
jobs:
    release:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Use PNPM
              uses: pnpm/action-setup@v3
            - name: Install Deps
              run: pnpm i
            - name: Init Git user
              run: |
                  git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
                  git config --global user.name "${GITHUB_ACTOR}"
            - name: Init NPM config
              run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Run release
              run: npm run release --ci
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
