name: Release & Publish to NPM
on: workflow_dispatch
jobs:
    release:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4
            - name: Install Deps
              run: pnpm ci
