name: Release & Publish to NPM
on: workflow_dispatch
jobs:
    release:
        runs-on: ubuntu-22.04
        steps:
            - name: Checkout source code
              uses: actions/checkout@v4
              with:
                  fetch-depth: 0
            - name: Authorize SSH
              uses: webfactory/ssh-agent@v0.9.0
              with:
                  ssh-private-key: ${{ secrets.SSH_KEY }}
            - name: Install Deps
              run: pnpm ci
            - name: Init Git user
              run: |
                  git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
                  git config --global user.name "${GITHUB_ACTOR}"
            - name: Init NPM config
              run: npm config set //registry.npmjs.org/:_authToken $NPM_TOKEN
              env:
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
            - name: Run release
              run: npm run release --ci
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
